# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
gems:             [jekyll-paginate]

# Setup
title:            'Peter Giuffrida'
tagline:          'The best IT professional ever'
description:      'I build robots made out of wood to hold other robots.'
url:              https://pgiuffrida.github.io
enforce_ssl:      pgiuffrida.github.io
baseurl:          /
author:
  name:           'Peter Giuffrida'
  url:            https://pgiuffrida.github.io

paginate:         5  # 5 posts per page
paginate_path:    '/projects/page:num/'

# Custom vars
version:          0.1

github:
  repo:           https://github.com/pgiuffrida/pgiuffrida.github.io
