# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Jonathan Giuffrida'
tagline:          'Adventures in Data Analysis and Bunnies'
description:      'I live at the intersection of quantitative analysis, healthcare, urban policy, and humanistic learning.'
url:              https://lucaluca.github.io
enforce_ssl:      lucaluca.github.io
baseurl:          /
author:
  name:           'Jonathan Giuffrida'
  url:            https://lucaluca.github.io

paginate:         5  # 5 posts per page
paginate_path:    '/projects/page:num/'

# Custom vars
version:          0.1

github:
  repo:           https://github.com/lucaluca/lucaluca.github.io
